export const properties = [
  { name: "Doge Meme NFT", price: "100 DOGE", color: "bg-yellow-300" },
  { name: "Smart Contract", type: "action", color: "bg-white", icon: "📜" },
  { name: "Rug Pull Avenue", price: "50 SAFE", color: "bg-red-500" },
  {
    name: "Gas Fee",
    price: "Pay 200 GWEI",
    type: "tax",
    color: "bg-white",
    icon: "⛽",
  },
  { name: "Diamond Hands Hodl", price: "150 BTC", color: "bg-blue-500" },
  { name: "Yield Farm", price: "200 CAKE", color: "bg-green-400" },
  { name: "Shill Street", price: "100 SHILL", color: "bg-purple-500" },
  { name: "Moon Base", price: "300 LUNA", color: "bg-gray-300" },
  { name: "HODL", type: "corner", color: "bg-white", icon: "💎" },
  { name: "Pump n' Dump Alley", price: "150 PUMP", color: "bg-orange-500" },
  { name: "Ethereum Gas Station", price: "200 ETH", color: "bg-indigo-600" },
  { name: "To The Moon!", type: "corner", color: "bg-white", icon: "🚀" },
  { name: "NFT Marketplace", price: "300 APE", color: "bg-green-600" },
  { name: "ICO", type: "action", color: "bg-white", icon: "💰" },
  { name: "Metaverse Manor", price: "350 META", color: "bg-blue-400" },
  { name: "DeFi Degen Street", price: "250 COMP", color: "bg-yellow-600" },
  { name: "Crypto Winter", type: "corner", color: "bg-white", icon: "❄️" },
  { name: "Web3 Startup Incubator", price: "400 VC", color: "bg-purple-600" },
  { name: "Airdrop", type: "action", color: "bg-white", icon: "🪂" },
  { name: "Lambo Dealership", price: "500 RICH", color: "bg-green-700" },
];
